name: op_expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


flutter_native_splash:

  color: "#7F3DFF"

  image: lib/core/assets/images/splash_screen/splash_screen_logo.png

  android_12:
   
    color: "#7F3DFF"

    image: lib/core/assets/images/splash_screen/splash_screen_logo.png



