name: op_expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  device_preview: ^1.2.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  google_sign_in: ^6.2.2
  google_sign_in_ios: ^5.7.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/onboarding/
    - lib/core/assets/icons/Magicons/Glyph/Arrow/
    - lib/core/assets/icons/Magicons/Outline/User Interface/
    - lib/core/assets/icons/
    - lib/core/assets/icons/Magicons/Glyph/User Interface/
    - lib/core/assets/images/verification_screen/
    - lib/core/assets/images/forgot_password_sent_screen/
    - lib/core/assets/icons/Magicons/Glyph/Arrow/
    - lib/core/assets/images/setup_wallet/
    - lib/core/assets/icons/Magicons/Glyph/Finance/
    - lib/core/assets/icons/Magicons/Glyph/Ecommerce & Shopping/
    - lib/core/assets/icons/Magicons/Glyph/Travel/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/core/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:

  color: "#7F3DFF"

  image: lib/core/assets/images/splash_screen/splash_screen_logo.png

  android_12:

    color: "#7F3DFF"

    image: lib/core/assets/images/splash_screen/splash_screen_logo.png
