name: op_expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/onboarding/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/core/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:

  color: "#7F3DFF"

  image: lib/core/assets/images/splash_screen/splash_screen_logo.png

  android_12:

    color: "#7F3DFF"

    image: lib/core/assets/images/splash_screen/splash_screen_logo.png
