// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIUcfhYnF6_FL1GFjjOZ_SW805AzWYGUw',
    appId: '1:290805600882:web:5f6a3a5ce11192b23b68eb',
    messagingSenderId: '290805600882',
    projectId: 'op-expense',
    authDomain: 'op-expense.firebaseapp.com',
    storageBucket: 'op-expense.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZ5C4O6TetTbzsloD5kDzb7CnsqLWymY',
    appId: '1:290805600882:android:a1fe0599248e4c703b68eb',
    messagingSenderId: '290805600882',
    projectId: 'op-expense',
    storageBucket: 'op-expense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHCx753RYtFiVwX6RYgofl9hm_FUwM-U',
    appId: '1:290805600882:ios:5db03af14a81a9b03b68eb',
    messagingSenderId: '290805600882',
    projectId: 'op-expense',
    storageBucket: 'op-expense.firebasestorage.app',
    iosBundleId: 'com.example.opExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIUcfhYnF6_FL1GFjjOZ_SW805AzWYGUw',
    appId: '1:290805600882:web:6e9c8099aab363153b68eb',
    messagingSenderId: '290805600882',
    projectId: 'op-expense',
    authDomain: 'op-expense.firebaseapp.com',
    storageBucket: 'op-expense.firebasestorage.app',
  );

}